# @package _global_

defaults:
  - /environment: env_oneshot

name: channel_generality
mode: train_ppo_oneshot
workdir: ${hydra:runtime.output_dir}

train_ppo_oneshot:
  environment: ${environment}
  env_updates:
    mode: training
    scenario_mode: inside
    model_name: scenario_0
    inside:
      training:
        active_scenario_list:
          - 0
      evaluating:
        active_scenario_list:
          - 0
      testing:
        active_scenario_list:
          - 0
