# @package _global_

defaults:
  - /environment: single_scenario_env
  - /agent: ray_agent

name: channel_generality
mode: train_ppo_baseline
workdir: ${hydra:runtime.output_dir}
train_scenario: 4

train_ppo_baseline:
  environment: ${environment}
  agent: ${agent}
  hydra_workdir: ${paths.channel_generality}/ppo_baseline/checkpoints/scenario_${train_scenario}/latest
  asset:
    use_versioned_runs: true
    model_root: ${paths.channel_generality}/ppo_baseline/checkpoints/scenario_${train_scenario}
    run_id: auto
    clean_before_run: false
    update_latest: true
    skip_when_finetune: true
  enable_finetune: true
  base_checkpoint_path: ${paths.channel_generality}/ppo_baseline/checkpoints/scenario_2/PPO_marl_comm_env_1fc0c_00000_0_2025-12-09_23-24-16/checkpoint_000045
  env_updates:
    mode: training
    scenario_mode: inside
    model_name: scenario_${train_scenario}
    inside:
      training:
        active_scenario_list:
          - ${train_scenario}

      testing:
        active_scenario_list:
          - ${train_scenario}

      evaluating:
        active_scenario_list:
          - ${train_scenario}