# @package _global_
defaults:
  - /simulation/channel_generality/_base
  - /simulation/channel_generality/defaults/ha_only
  - _self_

mode: train_dt_baseline

train_dt_baseline:
  dataset_dir: ${paths.channel_generality}/dt_baseline/dataset
  save_dir: ${paths.channel_generality}/dt_baseline/dt_model

  model:
    context_len: 20
    embed_dim: 512
    n_layer: 6
    n_head: 8
    activation: relu
    dropout: 0.1

  optimizer:
    epochs: 60
    batch_size: 1024
    lr: 1.0e-4
    rtg_scale: 100000.0
    total_epochs: null

  device: cuda
  grad_accum: 1
  resume_from: null
